<?php
define('BLOCKS_FLAG_PATH', __DIR__ . '/blocks_flag.json');
define('ROLE_WEBMESTRE', 'webmestre');
define('ROLE_SA', 'Super administrateur');

function check_blocks_flag($block_machine_name) {

    global $user;
    var_dump($user);

    // TODO : Mettre en cache le content
    $file_content = file_get_contents(BLOCKS_FLAG_PATH);
    $blocks_flag = json_decode($file_content, true);

    $host = $_SERVER['HTTP_HOST'];

    $is_visible = TRUE;
    $blocks = $blocks_flag[$host];
    $properties = $blocks[$block_machine_name];

    var_dump($blocks);
    if(isset($properties["is_visible"])) {
        $block_visibility = (bool) $properties["is_visible"];

        if(!$block_visibility && (!in_array(ROLE_WEBMESTRE, $user->roles) && !in_array(ROLE_SA, $user->roles))) {
            var_dump('On cache');
            $is_visible = FALSE;
        }

        if($is_visible) {
            $conditions = $properties["conditions"];
            if(isset($conditions["route"])) {
                if(arg(0) == 'node' && is_numeric(arg(1))) {
                    $route = drupal_get_path_alias(arg(0) . '/' . arg(1));
                    $is_visible = ($route == $conditions["route"]);
                }
            }
        }
    }

    return $is_visible;
}

?>