<?php

/**
 * Implements hook_install()
 */
function deployment_install() {
    for($i = 7001; $i < 7100; $i++) {
        $candidate = 'deployment_update_' . $i;
        if(function_exists($candidate)) $candidate();
    }
}

/**
 * Implements hook_update_N()
 */
function deployment_update_7001() {
    features_revert(array('article'));
}

function deployment_update_7002() {
    variable_set('admin_theme', 'seven');
    variable_set('clean_url', 1);
}
?>