<?php
define('PERMISSIONS_PATH', __DIR__ . '/config/permissions.json');

/**
 * Implements hook_install()
 */
function deployment_install() {
    for($i = 7001; $i < 7100; $i++) {
        $candidate = 'deployment_update_' . $i;
        if(function_exists($candidate)) $candidate();
    }

}

/**
 * Utilisé pour exposer une page pour les tests
 * Implements hook_menu()
 * @return mixed
 */
function deployment_menu() {

    $items['test-deployment'] = array(
        'title' => 'Deployment page',
        'page callback' => '_test',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function _test() {

    /*$file_content_access = file_get_contents(PERMISSIONS_PATH);
    $roles_access_to_active = json_decode($file_content_access, true);
    var_dump($roles_access_to_active);*/

    $visibility = check_blocks_flag('block_list_articles');
    print '---';
    var_dump($visibility);

    /*$modules = user_permission_get_modules();
    var_dump($modules);*/

    /*$rid = _get_rid_by_name('Super administrateur');
    //var_dump($rid);
    _set_user_permissions($rid, SA_ACCESS_PATH);*/

    return 'Test deployment';
}

/**
 * Implements hook_update_N()
 */
function deployment_update_7001() {
    features_revert(array('article'));
}

function deployment_update_7002() {
    variable_set('admin_theme', 'seven');
    variable_set('clean_url', 1);
}

function deployment_update_7003() {
    features_revert(array('article'));
}

function deployment_update_7004() {
    module_enable(array('fe_block'));
    features_revert(array('article'));
}

function deployment_update_7005() {
    theme_enable(array('deployment'));
    variable_set('theme_default', 'deployment');
    variable_set('node_admin_theme', 1);

    features_revert(array('accueil'));
    $nid = _create_node('page_d_accueil', 'Accueil');
    _set_new_role('Super administrateur', 3);
    variable_set('site_frontpage', 'node/' . $nid);
}

function deployment_update_7006() {
    module_enable(array('deployment_helper', 'menu', 'core_config_blocks'));
    features_revert(array('core_config_blocks'));
    _set_user_permissions('Super administrateur', PERMISSIONS_PATH);
}

function deployment_update_7007() {
    $rid = _get_rid_by_name('Super administrateur');
    _set_user_permissions($rid, PERMISSIONS_PATH);
}

function deployment_update_7008() {
    _create_base_user('mkeromen', 'mkeromen@absolunet.com', 'sa', 'Super administrateur');
}

function deployment_update_7009() {
    module_enable(array('menu_import'));
    $rid = _get_rid_by_name('Super administrateur');
    _set_user_permissions($rid, SA_ACCESS_PATH);

    menu_save(array(
        'menu_name' => 'menu-top-menu',
        'title' => 'Menu top',
        'description' => 'Super menu du haut'
    ));

    menu_import_file(__DIR__ . '/config/menu-top-menu-export.txt', 'menu-top-menu');
    features_revert(array('core_config_blocks'));
}

function deployment_update_7010() {
    module_enable(array('feature_flag', 'php', 'pathauto', 'content_page'));
    _set_user_permissions('Super administrateur', PERMISSIONS_PATH);

    features_revert(array('core_config_blocks', 'content_page'));
    variable_set('pathauto_node_pattern', '[node:title]');
}
?>