<?php
/**
 * Librairie d'aide pour la configuration des FEATURES
 * ! Ces fonctions ne doivent pas être utilisées pour migrer du contenu
 */

/**
 * Création d'utilisateur de base pour les rôles
 * webemestre/Super administrateur
 * @param $name
 * @param $mail
 * @param $pass
 * @param $role_name
 */
function _create_base_user($name, $mail, $pass, $role_name) {
    $rid = _get_rid_by_name($role_name);
    $fields = array(
        'name' => $name,
        'mail' => $mail,
        'pass' => $pass,
        'init' => $mail,
        'status' => 1,
        'roles' => array(
            $rid => $role_name
        )
    );

    user_save('', $fields);
}
/**
 * Création d'une node
 * pour le setup de page de configuration uniquement
 * comme la page d'accueil du site
 * @param $type
 * @param $title
 * @return mixed
 */
function _create_node($type, $title) {
    $node = new stdClass();
    $node->type = $type;
    $node->title = $title;
    $node->status = 1;
    $node->language = 'und';
    node_save($node);
    return $node->nid;
}

/**
 * Création d'un compte et setup des permissions (modules)
 * pour la configuration des comptes sa + webmestre
 * @param $role_name
 * @param $weight
 * @param $file_access_path
 */
function _set_new_role($role_name, $weight, $file_access_path) {

    if(_create_role($role_name, $weight)) {
        $rid = _get_rid_by_name($role_name);
        _set_user_permissions($rid, $file_access_path);
    }
}

/**
 * Setup des permissions
 * @param $rid
 * @param $file_access_path
 */
function _set_user_permissions($role_name, $permissions_path) {
    $rid = _get_rid_by_name($role_name);
    $file_content_access = file_get_contents($permissions_path);
    $roles_access_to_active = json_decode($file_content_access, true);
    user_role_change_permissions($rid, $roles_access_to_active[$role_name]);
}

/**
 * Création d'un rôle avec son poids
 * @param $name
 * @param $weight
 * @return boolean
 */
function _create_role($name, $weight) {
    $role = new stdClass();
    $role->name = $name;
    $role->weight = $weight;
    return user_role_save($role);
}

/**
 * Récupérer le rôle ID par le nom de rôle
 * @param $role_name
 * @return mixed
 */
function _get_rid_by_name($role_name) {
    $rid = db_select('role', 'r')
        ->fields('r', array('rid'))
        ->condition('name', $role_name, '=')
        ->execute()
        ->fetchField();

    return $rid;
}
?>